"""Add Guild.pinning_enabled

Revision ID: 0207b4540682
Revises: 839eafc8f325
Create Date: 2020-08-28 17:29:22.847348-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0207b4540682'
down_revision = '839eafc8f325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'guilds',
        sa.Column('pinning_enabled', sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE guilds SET pinning_enabled = true")
    op.alter_column('guilds', 'pinning_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'pinning_enabled')
    # ### end Alembic commands ###
