"""Add Guild.twitter_replies

Revision ID: 18ce384bb442
Revises: 314883886cb7
Create Date: 2020-11-14 19:26:35.305233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ce384bb442'
down_revision = '314883886cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('twitter_replies', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'twitter_replies')
    # ### end Alembic commands ###
