"""Add twitter_stream_id

Revision ID: 314883886cb7
Revises: 9c1e1af8c39b
Create Date: 2020-11-12 15:54:04.723534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314883886cb7'
down_revision = '9c1e1af8c39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('twitter_stream_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guilds', 'streams', ['twitter_stream_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guilds', type_='foreignkey')
    op.drop_column('guilds', 'twitter_stream_id')
    # ### end Alembic commands ###
