"""Add Guild.playlist_links

Revision ID: 647f0e805b70
Revises: 57747c829c50
Create Date: 2020-11-26 20:00:09.380223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647f0e805b70'
down_revision = '57747c829c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('playlist_links', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'playlist_links')
    # ### end Alembic commands ###
