"""Add last_message_id

Revision ID: 839eafc8f325
Revises: 1cfc5c97b01a
Create Date: 2020-08-28 17:04:04.544709-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839eafc8f325'
down_revision = '1cfc5c97b01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('latest_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'latest_message_id')
    # ### end Alembic commands ###
