"""Add unique indices

Revision ID: 9c1e1af8c39b
Revises: cf407f0c4d5e
Create Date: 2020-11-12 14:57:58.405417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1e1af8c39b'
down_revision = 'cf407f0c4d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("videos_video_id_guild_id", "videos", ["video_id", "guild_id"])
    op.create_unique_constraint("twitch_streams_twitch_id_guild_id", "twitch_streams", ["twitch_id", "guild_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("videos_video_id_guild_id", "videos")
    op.drop_constraint("twitch_streams_twitch_id_guild_id", "twitch_streams")
    # ### end Alembic commands ###
