"""Add twitch_streams table

Revision ID: cf407f0c4d5e
Revises: 253b7e993337
Create Date: 2020-11-12 14:52:49.323003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf407f0c4d5e'
down_revision = '253b7e993337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitch_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitch_streams')
    # ### end Alembic commands ###
