"""Delete videos table

Revision ID: fba6a6891390
Revises: 0207b4540682
Create Date: 2020-11-12 14:47:05.120762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba6a6891390'
down_revision = '0207b4540682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name='videos_guild_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='videos_pkey')
    )
    # ### end Alembic commands ###
